class_name Cast
extends RefCounted
## Everybody who lives in or visits the park: looks, personality, schedule, role.
## Names and descriptions are German (shown in the UI).

const PEOPLE := [
	{"id": "jens", "name": "Jogger Jens", "desc": "Schnell unterwegs, aber schnell aus der Puste.", "role": "jogger",
		"walk": 1.6, "run": 4.4, "rates": {"fatigue": 2.0, "hunger": 1.1},
		"hours": [[6, 11], [16, 21]], "likes": {"jog": 3.0, "sit": 0.6, "eat": 0.7, "chat": 0.4, "wander": 0.4},
		"look": {"height": 1.86, "girth": 0.92, "skin": "eac09c", "hair": "short", "hair_color": "c9a25c", "hat": "headband",
			"hat_color": "e8442e", "top": "tank", "top_color": "7ed957", "bottom": "shorts", "bottom_color": "222a35", "shoes": "f4f4f4"}},
	{"id": "herbert", "name": "Opa Herbert", "desc": "Langsam, liebt Bänke und Tauben. Schläft gern ein.", "role": "grandpa",
		"walk": 0.85, "run": 1.7, "rates": {"fatigue": 1.6, "joy": 0.7},
		"hours": [[8, 19]], "likes": {"sit": 2.5, "sleep": 2.5, "feed_pigeons": 2.2, "chess": 0.8, "chat": 1.2, "wander": 0.4, "read": 1.0},
		"look": {"height": 1.68, "girth": 1.18, "skin": "f0c8a8", "hair": "bald_ring", "hair_color": "d8d8d8", "beard": "mustache",
			"hat": "flatcap", "hat_color": "6b4a32", "glasses": "round", "top": "shirt", "top_color": "c8b48a",
			"bottom": "pants", "bottom_color": "5a4a3a", "shoes": "3a2a20", "nose": 1.4}},
	{"id": "peggy", "name": "Touristin Peggy", "desc": "Aus Texas. Fotografiert alles, verläuft sich, hat immer Hunger.", "role": "tourist",
		"walk": 1.15, "run": 2.6, "rates": {"hunger": 1.8},
		"hours": [[10, 19]], "likes": {"photo": 2.5, "lost": 1.4, "eat": 1.8, "wander": 1.2, "chat": 1.0, "watch": 1.4},
		"look": {"height": 1.66, "girth": 1.15, "skin": "f5d0b5", "hair": "bob", "hair_color": "e8d39a", "hat": "sunhat",
			"hat_color": "f2e2b0", "glasses": "sun", "top": "tshirt", "top_color": "f08ac0", "bottom": "shorts",
			"bottom_color": "c8b48a", "shoes": "f4f4f4", "extras": ["backpack", "camera_strap"], "blush": true}},
	{"id": "heinz", "name": "Hot-Dog-Heinz", "desc": "Verkauft die besten Hot Dogs der Stadt. Sagt er.", "role": "vendor",
		"walk": 1.1, "hours": [[9, 21]], "likes": {"sit": 0.5, "eat": 0.3},
		"work": {"type": "shop", "shop": "hotdog_stand", "hours": [10, 20]},
		"look": {"height": 1.76, "girth": 1.35, "skin": "eac09c", "hair": "short", "hair_color": "4a2f1e", "beard": "mustache",
			"hat": "cap", "hat_color": "d8402e", "top": "apron", "top_color": "f4c542", "bottom": "pants", "bottom_color": "333a44"}},
	{"id": "dora", "name": "Donut-Dora", "desc": "Backt Donuts mit Liebe und Streuseln.", "role": "vendor",
		"walk": 1.1, "hours": [[7, 20]], "likes": {"sit": 0.5},
		"work": {"type": "shop", "shop": "donut_stand", "hours": [8, 19]},
		"look": {"height": 1.64, "girth": 1.12, "skin": "d9a77e", "hair": "bun", "hair_color": "b0442a", "top": "apron",
			"top_color": "f28db2", "bottom": "skirt", "bottom_color": "8a3a5a", "blush": true, "extras": ["necklace"]}},
	{"id": "kemal", "name": "Kiosk-Kemal", "desc": "Hat immer einen Spruch und Entenbrot parat.", "role": "vendor",
		"walk": 1.2, "hours": [[6, 23]], "likes": {"sit": 0.4},
		"work": {"type": "shop", "shop": "kiosk", "hours": [7, 22]},
		"look": {"height": 1.78, "girth": 1.05, "skin": "b47d57", "hair": "short", "hair_color": "1a1410", "beard": "full",
			"hair_style": "short", "top": "shirt", "top_color": "3f7cc2", "bottom": "pants", "bottom_color": "2a2a30"}},
	{"id": "mia", "name": "Hundesitterin Mia", "desc": "Führt fünf Hunde gleichzeitig aus. Meistens.", "role": "dogsitter",
		"walk": 1.35, "run": 3.4, "hours": [[9, 18]], "dogs": ["bello", "luna", "rex", "kruemel", "fiffi"],
		"likes": {"sit": 0.6, "chat": 0.8, "eat": 0.8},
		"work": {"type": "dogwalk"},
		"look": {"height": 1.7, "girth": 0.95, "skin": "f5d0b5", "hair": "ponytail", "hair_color": "7a4a26", "top": "hoodie",
			"top_color": "3aa86b", "bottom": "pants", "bottom_color": "2a2a35", "shoes": "e8442e"}},
	{"id": "boris", "name": "Schachspieler Boris", "desc": "Hat seit 1983 keine Partie verloren. Angeblich.", "role": "chess",
		"walk": 1.0, "hours": [[10, 20]], "likes": {"eat": 0.6, "chat": 0.3},
		"work": {"type": "chess", "dry": true},
		"look": {"height": 1.8, "girth": 1.1, "skin": "f0c8a8", "hair": "short", "hair_color": "9a9a9a", "beard": "full",
			"glasses": "square", "top": "jacket", "top_color": "6a4a32", "bottom": "pants", "bottom_color": "3a3a3a", "hat": "flatcap", "hat_color": "3a3a3a"}},
	{"id": "pierre", "name": "Pantomime Pierre", "desc": "Spricht nie. Steckt oft in unsichtbaren Kisten fest.", "role": "mime",
		"walk": 1.1, "hours": [[11, 18]], "likes": {"eat": 0.5, "sit": 0.3},
		"work": {"type": "perform", "spot": "mime", "anim": "mime", "dry": true, "lines": ["…", "(gestikuliert wild)", "(verbeugt sich)"]},
		"look": {"height": 1.74, "girth": 0.88, "skin": "f6f2ec", "hair": "short", "hair_color": "1a1410", "hat": "beret",
			"hat_color": "1a1a1a", "top": "striped", "top_color": "1a1a1a", "top_color2": "f4f4f4", "bottom": "pants",
			"bottom_color": "1a1a1a", "extras": ["gloves"]}},
	{"id": "thorsten", "name": "Business-Thorsten", "desc": "Telefoniert pausenlos. Mittagspause im Park.", "role": "business",
		"walk": 1.55, "run": 3.5, "hours": [[8, 18]], "likes": {"phone": 2.4, "eat": 1.2, "sit": 0.5, "wander": 0.3},
		"look": {"height": 1.83, "girth": 1.0, "skin": "eac09c", "hair": "short", "hair_color": "2b1d14", "top": "suit",
			"top_color": "4a4e58", "tie": "a8322a", "bottom": "pants", "bottom_color": "3a3e48", "shoes": "1a1a1a"}},
	{"id": "gertrud", "name": "Oma Gertrud", "desc": "Füttert die Enten seit fünfzig Jahren.", "role": "granny",
		"walk": 0.8, "run": 1.4, "rates": {"fatigue": 1.5},
		"hours": [[9, 17]], "likes": {"feed_ducks": 3.0, "sit": 1.8, "chat": 1.5, "sleep": 0.8},
		"look": {"height": 1.58, "girth": 1.15, "skin": "f5d0b5", "hair": "bun", "hair_color": "e8e8e8", "glasses": "round",
			"top": "dress", "top_color": "8e6fb0", "extras": ["scarf"], "scarf_color": "e8d0f0", "shoes": "5a3a4a", "blush": true}},
	{"id": "lena", "name": "Lena", "desc": "Acht Jahre alt, findet manchmal unsichtbare Dinge.", "role": "kid",
		"walk": 1.3, "run": 3.6, "rates": {"fatigue": 0.6, "hunger": 1.2},
		"hours": [[9, 18]], "likes": {"play": 3.5, "eat": 0.8, "chat": 0.4},
		"look": {"child": true, "height": 1.2, "skin": "f5d0b5", "hair": "pigtails", "hair_color": "c9a25c", "top": "dress",
			"top_color": "f2c230", "shoes": "e8442e", "blush": true}},
	{"id": "sabine", "name": "Mama Sabine", "desc": "Behält Lena im Blick. Und ihr Handy.", "role": "parent",
		"walk": 1.25, "hours": [[9, 18]], "likes": {"sit": 2.5, "read": 1.5, "chat": 1.0, "eat": 0.6},
		"look": {"height": 1.69, "skin": "f5d0b5", "hair": "ponytail", "hair_color": "e8d39a", "top": "jacket",
			"top_color": "3aa8a0", "bottom": "pants", "bottom_color": "4a5a7a"}},
	{"id": "kalle", "name": "Gärtner Kalle", "desc": "Hält den Park in Schuss. Hasst Pfandflaschen im Gebüsch.", "role": "gardener",
		"walk": 1.15, "hours": [[7, 16]], "likes": {"eat": 0.6, "sit": 0.6},
		"work": {"type": "garden"},
		"look": {"height": 1.81, "girth": 1.1, "skin": "d9a77e", "hair": "short", "hair_color": "7a4a26", "beard": "stubble",
			"hat": "cap", "hat_color": "3a7a3a", "top": "shirt", "top_color": "4a7a3a", "bottom": "pants", "bottom_color": "3a5a3a",
			"extras": ["vest"]}},
	{"id": "lukas", "name": "Student Lukas", "desc": "Spielt Frisbee mit Balu, statt zu lernen.", "role": "student",
		"walk": 1.3, "run": 3.6, "hours": [[12, 20]], "dogs": ["balu"],
		"likes": {"sit": 0.8, "eat": 1.0, "chat": 0.8, "read": 0.6},
		"work": {"type": "fetch", "hours": [13, 18], "dry": true},
		"look": {"height": 1.82, "girth": 0.95, "skin": "8d5a3b", "hair": "curly", "hair_color": "1a1410", "glasses": "round",
			"top": "hoodie", "top_color": "c0392b", "bottom": "pants", "bottom_color": "3a4a6a"}},
	{"id": "jacques", "name": "Monsieur Jacques", "desc": "Boule ist für ihn kein Spiel, sondern Philosophie.", "role": "boule",
		"walk": 1.05, "hours": [[10, 19]], "likes": {"sit": 1.0, "eat": 0.8, "chat": 1.2},
		"work": {"type": "perform", "spot": "boule", "anim": "throw", "dry": true, "lines": ["Allez!", "Magnifique!", "Oh là là …", "Wer spielt mit mir?"]},
		"look": {"height": 1.72, "girth": 1.15, "skin": "f0c8a8", "hair": "short", "hair_color": "9a9a9a", "beard": "mustache",
			"hat": "beret", "hat_color": "2b4a8a", "top": "striped", "top_color": "2b4a8a", "top_color2": "f4f4f4",
			"bottom": "pants", "bottom_color": "c8b48a"}},
	{"id": "harry", "name": "Hütchen-Harry", "desc": "Wo ist die Nuss? Sicher nicht da, wo du denkst.", "role": "hustler",
		"walk": 1.2, "hours": [[11, 20]], "likes": {"eat": 0.6, "sit": 0.4},
		"work": {"type": "perform", "spot": "shell", "anim": "talk", "dry": true,
			"lines": ["Hütchen, Hütchen! Wo ist die Nuss?", "Nur zwei Euro! Doppelt oder nichts!", "Kommen Sie näher!"]},
		"look": {"height": 1.75, "girth": 0.95, "skin": "eac09c", "hair": "short", "hair_color": "2b1d14", "beard": "goatee",
			"hat": "tophat", "glasses": "sun", "top": "jacket", "top_color": "2a2a2a", "bottom": "pants", "bottom_color": "4a2a2a"}},
	{"id": "ricarda", "name": "Musikerin Ricarda", "desc": "Spielt nachmittags Gitarre im Pavillon.", "role": "musician",
		"walk": 1.15, "hours": [[13, 22]], "likes": {"eat": 0.8, "sit": 0.6, "chat": 0.6},
		"work": {"type": "perform", "spot": "pavilion", "anim": "guitar", "item": "guitar", "hours": [14, 21],
			"lines": ["Lalala, la-laaa …", "Danke, danke!", "Das nächste Lied ist für die Enten."]},
		"look": {"height": 1.7, "skin": "f5d0b5", "hair": "long", "hair_color": "8e44ad", "top": "tshirt", "top_color": "2a2a2a",
			"bottom": "skirt", "bottom_color": "3a3a5a", "socks": "1a1a1a", "extras": ["necklace"]}},
	{"id": "yvonne", "name": "Yoga-Yvonne", "desc": "Begrüßt jeden Morgen die Sonne.", "role": "yogi",
		"walk": 1.2, "hours": [[7, 13]], "likes": {"yoga": 3.0, "sit": 0.5, "eat": 0.6, "chat": 0.6},
		"look": {"height": 1.72, "girth": 0.9, "skin": "d9a77e", "hair": "bun", "hair_color": "2b1d14", "top": "tank",
			"top_color": "3aa8a0", "bottom": "pants", "bottom_color": "6a3a8a"}},
	{"id": "anna", "name": "Anna", "desc": "Frisch verliebt. Picknick mit Ben.", "role": "lover",
		"walk": 1.1, "hours": [[12, 20]], "likes": {"picnic": 2.5, "chat": 1.5, "wander": 1.0, "eat": 0.8},
		"look": {"height": 1.68, "skin": "f5d0b5", "hair": "long", "hair_color": "b0442a", "top": "dress", "top_color": "e8574a", "blush": true}},
	{"id": "ben", "name": "Ben", "desc": "Hat das Picknick vorbereitet. Mit Liebe und Senf.", "role": "lover",
		"walk": 1.1, "hours": [[12, 20]], "likes": {"picnic": 2.5, "chat": 1.5, "wander": 1.0, "eat": 0.8},
		"look": {"height": 1.8, "skin": "b47d57", "hair": "short", "hair_color": "1a1410", "top": "shirt", "top_color": "f4f4f4",
			"bottom": "pants", "bottom_color": "c8b48a"}},
	{"id": "nico", "name": "Nachtschwärmer Nico", "desc": "Kommt raus, wenn alle anderen schlafen.", "role": "nightowl",
		"walk": 1.25, "run": 3.5, "hours": [[20, 27]], "likes": {"dance": 2.0, "sit": 1.0, "wander": 1.0, "chat": 0.5},
		"look": {"height": 1.77, "skin": "eac09c", "hair": "mohawk", "hair_color": "3aa8e0", "top": "hoodie", "top_color": "2a2a3a",
			"bottom": "pants", "bottom_color": "1a1a1a", "extras": ["necklace"]}},
	{"id": "bruno", "name": "Brückentroll Bruno", "desc": "Wohnt unter der Steinbrücke. Liebt Rätsel.", "role": "troll",
		"species": "troll", "walk": 0.9, "hours": [[22, 28]], "likes": {},
		"work": {"type": "perform", "spot": "bridge_troll", "anim": "idle", "lines": ["Wer stört meinen Schlaf?", "Hrmpf.", "Ein Rätsel gefällig?"]},
		"look": {"height": 2.05, "girth": 1.5, "skin": "7a9a5a", "hair": "spiky", "hair_color": "4a5a2a", "beard": "long",
			"top": "tank", "top_color": "6b4a32", "bottom": "shorts", "bottom_color": "4a3a2a", "nose": 2.2, "shoes": "4a3a2a"}},
]

## Generic visitors get random looks and names.
const VISITOR_NAMES := ["Klara", "Jonas", "Fatma", "Igor", "Svenja", "Mehmet", "Greta", "Paul", "Ayşe", "Hannes", "Lotte", "Mustafa"]

const ANIMALS := [
	{"id": "bello", "name": "Dackel Bello", "desc": "Klein, aber mutig. Bellt alles an.", "species": "dog", "preset": "dachshund",
		"walk": 1.4, "run": 3.6, "owner": "mia", "look": {"collar": "c0392b"}, "radius": 0.25},
	{"id": "luna", "name": "Pudel Luna", "desc": "Frisch frisiert und sehr eitel.", "species": "dog", "preset": "poodle",
		"walk": 1.4, "run": 4.0, "owner": "mia", "look": {"collar": "e84393"}, "radius": 0.3},
	{"id": "rex", "name": "Schäferhund Rex", "desc": "Pflichtbewusst. Bewacht den Park.", "species": "dog", "preset": "shepherd",
		"walk": 1.5, "run": 5.0, "owner": "mia", "look": {"collar": "2a2a2a"}, "radius": 0.4},
	{"id": "kruemel", "name": "Mops Krümel", "desc": "Schnauft viel, frisst mehr.", "species": "dog", "preset": "pug",
		"walk": 1.2, "run": 2.8, "owner": "mia", "rates": {"hunger": 1.6, "fatigue": 1.5}, "look": {"collar": "3a7fd8"}, "radius": 0.3},
	{"id": "fiffi", "name": "Terrier Fiffi", "desc": "Hat immer gute Laune.", "species": "dog", "preset": "terrier",
		"walk": 1.5, "run": 4.4, "owner": "mia", "look": {"collar": "f2c230"}, "radius": 0.28},
	{"id": "balu", "name": "Labrador Balu", "desc": "Frisbee-Weltmeister (inoffiziell).", "species": "dog", "preset": "labrador",
		"walk": 1.5, "run": 5.2, "owner": "lukas", "look": {"collar": "27ae60"}, "radius": 0.4},
	{"id": "minka", "name": "Katze Minka", "desc": "Wohnt am Kiosk. Jagt Mäuse, fängt nie eine.", "species": "cat", "preset": "cat",
		"walk": 1.0, "run": 4.0, "home": [8, 62], "radius": 0.25},
	{"id": "mikesch", "name": "Kater Mikesch", "desc": "Schwarz wie die Nacht, mit weißen Söckchen.", "species": "cat", "preset": "cat_black",
		"walk": 1.0, "run": 4.2, "home": [-88, -44], "radius": 0.25},
	{"id": "pieps", "name": "Maus Pieps", "desc": "Klein, flink und immer auf Krümelsuche.", "species": "mouse", "preset": "mouse",
		"walk": 0.9, "run": 2.6, "home": [10.5, 61.5], "radius": 0.1},
	{"id": "fiep", "name": "Maus Fiep", "desc": "Pieps' kleine Schwester.", "species": "mouse", "preset": "mouse",
		"walk": 0.9, "run": 2.6, "home": [-3, 55], "radius": 0.1},
	{"id": "kruemelmaus", "name": "Maus Krümel", "desc": "Wohnt unter dem Pavillon.", "species": "mouse", "preset": "mouse",
		"walk": 0.9, "run": 2.6, "home": [-17, -45], "radius": 0.1},
	{"id": "erwin", "name": "Erpel Erwin", "desc": "Der Chef im Teich. Quakt am lautesten.", "species": "duck", "preset": "drake",
		"walk": 0.7, "run": 1.6, "swims": true, "home": [45, 6], "radius": 0.25},
	{"id": "frieda", "name": "Ente Frieda", "desc": "Mama von vier Küken.", "species": "duck", "preset": "hen",
		"walk": 0.65, "run": 1.4, "swims": true, "home": [45, 6], "radius": 0.25},
	{"id": "klecks", "name": "Küken Klecks", "desc": "Folgt Mama überallhin.", "species": "duckling", "preset": "duckling",
		"walk": 0.8, "run": 1.8, "swims": true, "mother": "frieda", "follow_index": 1, "radius": 0.1},
	{"id": "flecki", "name": "Küken Flecki", "desc": "Der Neugierigste.", "species": "duckling", "preset": "duckling",
		"walk": 0.8, "run": 1.8, "swims": true, "mother": "frieda", "follow_index": 2, "radius": 0.1},
	{"id": "puenktchen", "name": "Küken Pünktchen", "desc": "Immer ein bisschen hinterher.", "species": "duckling", "preset": "duckling",
		"walk": 0.8, "run": 1.8, "swims": true, "mother": "frieda", "follow_index": 3, "radius": 0.1},
	{"id": "wuschel", "name": "Küken Wuschel", "desc": "Das Kleinste.", "species": "duckling", "preset": "duckling",
		"walk": 0.8, "run": 1.8, "swims": true, "mother": "frieda", "follow_index": 4, "radius": 0.1},
	{"id": "quaki", "name": "Ente Quaki", "desc": "Liebt Brotkrumen über alles.", "species": "duck", "preset": "drake",
		"walk": 0.7, "run": 1.6, "swims": true, "home": [40, 12], "radius": 0.25},
	{"id": "lotte", "name": "Ente Lotte", "desc": "Schwimmt am liebsten im Bach.", "species": "duck", "preset": "hen",
		"walk": 0.7, "run": 1.6, "swims": true, "home": [52, 10], "radius": 0.25},
	{"id": "fritz", "name": "Erpel Fritz", "desc": "Erwins ewiger Rivale.", "species": "duck", "preset": "drake",
		"walk": 0.7, "run": 1.6, "swims": true, "home": [36, 2], "radius": 0.25},
	{"id": "watschel", "name": "Ente Watschel", "desc": "Geht lieber zu Fuß als zu schwimmen.", "species": "duck", "preset": "hen",
		"walk": 0.7, "run": 1.6, "swims": true, "home": [56, 2], "radius": 0.25},
	{"id": "gustav", "name": "Gans Gustav", "desc": "Gierig, laut, unberechenbar.", "species": "goose", "preset": "goose",
		"walk": 0.9, "run": 2.4, "swims": true, "home": [48, 12], "radius": 0.35},
	{"id": "nussi", "name": "Eichhörnchen Nussi", "desc": "Klaut Donuts. Hat ein geheimes Versteck.", "species": "squirrel", "preset": "squirrel",
		"walk": 1.6, "run": 5.0, "thief": true, "home": [0, 40], "radius": 0.12},
	{"id": "flitz", "name": "Eichhörnchen Flitz", "desc": "Schneller als sein Schatten.", "species": "squirrel", "preset": "squirrel",
		"walk": 1.6, "run": 5.4, "home": [-60, -60], "radius": 0.12},
	{"id": "hasel", "name": "Eichhörnchen Hasel", "desc": "Vergräbt Nüsse und vergisst sie wieder.", "species": "squirrel", "preset": "squirrel",
		"walk": 1.6, "run": 5.0, "home": [60, -40], "radius": 0.12},
	{"id": "gurrmann", "name": "Taube Gurrmann", "desc": "Anführer der Bank-Tauben.", "species": "pigeon", "preset": "pigeon",
		"walk": 0.8, "run": 1.6, "home": [-56, 27], "radius": 0.15},
	{"id": "taube2", "name": "Taube Grauchen", "desc": "Gurrt gern mit.", "species": "pigeon", "preset": "pigeon",
		"walk": 0.8, "run": 1.6, "home": [-48, 22], "radius": 0.15},
	{"id": "taube3", "name": "Taube Pick", "desc": "Pickt alles auf.", "species": "pigeon", "preset": "pigeon",
		"walk": 0.8, "run": 1.6, "home": [-64, 12], "radius": 0.15},
	{"id": "taube4", "name": "Taube Ruckedigu", "desc": "Wohnt am Imbissplatz.", "species": "pigeon", "preset": "pigeon",
		"walk": 0.8, "run": 1.6, "home": [6, 48], "radius": 0.15},
	{"id": "taube5", "name": "Taube Flatter", "desc": "Fliegt beim kleinsten Geräusch auf.", "species": "pigeon", "preset": "pigeon",
		"walk": 0.8, "run": 1.6, "home": [8, 46], "radius": 0.15},
	{"id": "rudi", "name": "Reiher Rudi", "desc": "Steht stundenlang im Bach. Geduldig.", "species": "heron", "preset": "heron",
		"walk": 0.8, "run": 1.5, "playable": false, "radius": 0.3},
	{"id": "eulalia", "name": "Eule Eulalia", "desc": "Nur nachts wach. Weiß alles.", "species": "owl", "preset": "owl",
		"walk": 0.5, "home": [-24, -40], "playable": false, "radius": 0.2},
	{"id": "stachel", "name": "Igel Stachel", "desc": "Nachts unterwegs auf Schneckensuche.", "species": "hedgehog", "preset": "hedgehog",
		"walk": 0.5, "run": 1.2, "home": [-100, 30], "radius": 0.15},
	{"id": "fridolin", "name": "Fuchs Fridolin", "desc": "Schlau, scheu und nachts am Mülleimer.", "species": "fox", "preset": "fox",
		"walk": 1.3, "run": 5.0, "home": [100, -60], "radius": 0.3},
]


## Random visitor definition.
static func visitor(i: int, rng: RandomNumberGenerator) -> Dictionary:
	var name: String = VISITOR_NAMES[i % VISITOR_NAMES.size()]
	var female := i % 2 == 0
	var tops := ["tshirt", "shirt", "hoodie", "jacket", "dress" if female else "tshirt"]
	var hairs := ["long", "bob", "ponytail", "bun", "curly"] if female else ["short", "spiky", "curly", "short", "bald_ring"]
	var cols := ["e8574a", "3f7cc2", "3aa86b", "f2c230", "8e44ad", "e0752d", "2c3e50", "f4f4f4", "c0392b", "16a085"]
	var top: String = tops[rng.randi() % tops.size()]
	var age := rng.randf()
	var look := {
		"height": rng.randf_range(1.6, 1.78) if female else rng.randf_range(1.7, 1.9),
		"girth": rng.randf_range(0.9, 1.3),
		"skin": HumanRig.SKIN_TONES[rng.randi() % HumanRig.SKIN_TONES.size()],
		"hair": hairs[rng.randi() % hairs.size()],
		"hair_color": HumanRig.HAIR_COLORS[rng.randi() % (8 if age > 0.8 else 6)],
		"top": top, "top_color": cols[rng.randi() % cols.size()],
		"bottom": ["pants", "shorts", "skirt" if female else "pants"][rng.randi() % 3],
		"bottom_color": ["2a3a5a", "3a3a3a", "c8b48a", "5a4a3a"][rng.randi() % 4],
		"glasses": ["", "", "round", "square", "sun"][rng.randi() % 5],
		"hat": ["", "", "", "cap", "beanie", "bucket", "sunhat" if female else "flatcap"][rng.randi() % 7],
		"hat_color": cols[rng.randi() % cols.size()],
		"beard": "" if female else ["", "", "stubble", "full", "mustache"][rng.randi() % 5],
		"extras": [["", "backpack", "scarf", "necklace"][rng.randi() % 4]],
	}
	var kinds := [
		{"desc": "Genießt einfach den Tag im Park.", "likes": {"wander": 1.5, "sit": 1.2, "eat": 1.0, "chat": 1.2, "watch": 1.2}},
		{"desc": "Liest gern auf der Parkbank.", "likes": {"read": 2.0, "sit": 1.0, "eat": 0.8, "wander": 0.6}},
		{"desc": "Joggt ab und zu eine Runde.", "likes": {"jog": 1.6, "wander": 0.8, "sit": 0.6, "eat": 0.6}},
		{"desc": "Ist zum Fotografieren hier.", "likes": {"photo": 1.6, "wander": 1.0, "eat": 1.0, "watch": 1.0}},
		{"desc": "Füttert gern die Enten.", "likes": {"feed_ducks": 1.6, "sit": 1.0, "wander": 0.8, "chat": 1.0}},
	]
	var k: Dictionary = kinds[rng.randi() % kinds.size()]
	var start := rng.randi_range(7, 14)
	return {"id": "visitor_%d" % i, "name": "Besucher%s %s" % ["in" if female else "", name], "desc": k["desc"],
		"role": "visitor", "walk": rng.randf_range(1.05, 1.4), "hours": [[start, start + rng.randi_range(4, 9)]],
		"likes": k["likes"], "look": look}
